server:
  port: 8888
spring:
  mvc:
    view:
      prefix: /
      suffix: .jsp
  application:
    name: springboot-shiro-jsp
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.43.197:3306/d_shiro2?serverTimezone=UTC&useSSL=false
    username: root
    password:
  redis:
    port: 6379
    database: 0   #使用redis的0号库
    host: localhost
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.xsx.boot.model




